In [45]:
import pandas as pd
from pathlib import Path

input_path = Path("resources") / "pretrain" / "partial_dataset_info.csv"
df_input = pd.read_csv(input_path)
df_input.head()

                               name  ...      category
0                     bdg-2_panther  ...   small_clean
1                         bdg-2_fox  ...   small_clean
2                         bdg-2_rat  ...   small_clean
3                        bdg-2_bear  ...   small_clean
4  london_smart_meters_with_missing  ...  noisy_sparse

[5 rows x 9 columns]

In [46]:
output_path = input_path.parent / "dataset_info.csv"
df_output = pd.read_csv(output_path)
df_output.head()

         name    term freq  ...  _min_series_length  sum_series_length   domain
0        bull   short    H  ...               17544             719304   Energy
1        bull  medium    H  ...               17544             719304   Energy
2        bull    long    H  ...               17544             719304   Energy
3  cmip6_1885   short   6H  ...                7300         3169484800  Climate
4  cmip6_1885  medium   6H  ...                7300         3169484800  Climate

[5 rows x 9 columns]

In [47]:
df_output["domain"] = ""
df_output.to_csv(output_path, index=False)

In [48]:
for i, input_row in df_input.iterrows():
    for j, output_row in df_output.iterrows():
        if input_row["name"] == output_row["name"]:
            df_output.at[j, "domain"] = input_row["domain"]


df_output.to_csv(output_path, index=False)

In [49]:
num_empty = (df_output["domain"] == "").sum()
num_empty

201

In [50]:
for i, input_row in df_input.iterrows():
    cleaned_name = input_row["name"].split("_")[0]

    indices = []

    for j, output_row in df_output.iterrows():
        if output_row["name"].startswith(cleaned_name):
            indices.append(j)

    for index in indices:
        df_output.at[index, "domain"] = input_row["domain"]


df_output.to_csv(output_path, index=False)

In [51]:
num_empty = (df_output["domain"] == "").sum()
print(num_empty)
print(df_output[df_output["domain"] == ""])

3
    name    term freq  ...  _min_series_length  sum_series_length  domain
387  lcl   short    H  ...                 193            9543553
388  lcl  medium    H  ...                 193            9543553
389  lcl    long    H  ...                 193            9543553

[3 rows x 9 columns]

In [52]:
df_output.loc[df_output["domain"] == "", "domain"] = "Energy"
print(df_output.iloc[387:390])

    name    term freq  ...  _min_series_length  sum_series_length  domain
387  lcl   short    H  ...                 193            9543553  Energy
388  lcl  medium    H  ...                 193            9543553  Energy
389  lcl    long    H  ...                 193            9543553  Energy

[3 rows x 9 columns]

In [54]:
num_empty = (df_output["domain"] == "").sum()
print(num_empty)
print(df_output[df_output["domain"] == ""])
df_output.to_csv(output_path, index=False)

0
Empty DataFrame
Columns: [name, term, freq, prediction_length, target_dim, windows, _min_series_length, sum_series_length, domain]
Index: []